apiVersion: v1
entries:
  elasticsearch:
  - apiVersion: v1
    appVersion: 7.13.3
    created: "2023-03-22T15:50:43.570215388Z"
    description: Official Elastic helm chart for Elasticsearch
    digest: 9f429d9acc7b7f6c2c12404685e6537a1b62a78398401a48a10cddbe9ca10294
    home: https://github.com/elastic/helm-charts
    icon: https://helm.elastic.co/icons/elasticsearch.png
    maintainers:
    - email: helm-charts@elastic.co
      name: Elastic
    name: elasticsearch
    sources:
    - https://github.com/elastic/elasticsearch
    urls:
    - https://github.com/AFC-AI2C/coeus-ltac-helm-charts.git/elk/elasticsearch-7.13.3.tgz
    version: 7.13.3
  filebeat:
  - apiVersion: v1
    appVersion: 7.13.3
    created: "2023-03-22T15:50:43.572107537Z"
    description: Official Elastic helm chart for Filebeat
    digest: 7b3ca5b89b9ef11daf9abf573c8d1ade2762a19b3f14e7d5ec0a2b27e011a0ce
    home: https://github.com/elastic/helm-charts
    icon: https://helm.elastic.co/icons/beats.png
    maintainers:
    - email: helm-charts@elastic.co
      name: Elastic
    name: filebeat
    sources:
    - https://github.com/elastic/beats
    urls:
    - https://github.com/AFC-AI2C/coeus-ltac-helm-charts.git/elk/filebeat-7.13.3.tgz
    version: 7.13.3
  gitlab:
  - apiVersion: v1
    appVersion: 15.3.1
    created: "2023-03-22T15:50:43.566864589Z"
    dependencies:
    - name: gitlab
      repository: ""
      version: '*.*.*'
    - name: certmanager-issuer
      repository: ""
      version: '*.*.*'
    - name: minio
      repository: ""
      version: '*.*.*'
    - name: registry
      repository: ""
      version: '*.*.*'
    - alias: certmanager
      condition: certmanager.install
      name: cert-manager
      repository: https://ltac.dev.local:5000
      version: 1.5.4
    - condition: prometheus.install
      name: prometheus
      repository: https://ltac.dev.local:5000helm-charts
      version: 15.0.4
    - condition: postgresql.install
      name: postgresql
      repository: https://ltac.dev.local:5000bitnami/charts/eb5f9a9513d987b519f0ecd732e7031241c50328/bitnami
      version: 8.9.4
    - condition: gitlab-runner.install
      name: gitlab-runner
      repository: https://ltac.dev.local:5000
      version: 0.43.1
    - condition: global.grafana.enabled
      name: grafana
      repository: https://ltac.dev.local:5000helm-charts
      version: 6.11.0
    - condition: redis.install
      name: redis
      repository: https://ltac.dev.local:5000bitnami/charts/eb5f9a9513d987b519f0ecd732e7031241c50328/bitnami
      version: 11.3.4
    - condition: nginx-ingress.enabled
      name: nginx-ingress
      repository: ""
      version: '*.*.*'
    description: The One DevOps Platform
    digest: fe83c2bf397f8c37d264ed6f891519ef4e591c1c462d8968cd7a0344a32032cc
    home: https://about.gitlab.com/
    icon: https://gitlab.com/gitlab-com/gitlab-artwork/raw/master/logo/logo-square.png
    keywords:
    - gitlab
    maintainers:
    - email: support@gitlab.com
      name: GitLab Inc.
    name: gitlab
    sources:
    - https://gitlab.com/gitlab-org/charts/gitlab
    urls:
    - https://github.com/AFC-AI2C/coeus-ltac-helm-charts.git/gitlab-6.3.1.tgz
    version: 6.3.1
  kibana:
  - apiVersion: v1
    appVersion: 7.13.3
    created: "2023-03-22T15:50:43.573639616Z"
    description: Official Elastic helm chart for Kibana
    digest: d3297aef126d4dd3219b6063c210dc1d837c9727bc2f74e3a2ad53a9e58cee16
    home: https://github.com/elastic/helm-charts
    icon: https://helm.elastic.co/icons/kibana.png
    maintainers:
    - email: helm-charts@elastic.co
      name: Elastic
    name: kibana
    sources:
    - https://github.com/elastic/kibana
    urls:
    - https://github.com/AFC-AI2C/coeus-ltac-helm-charts.git/elk/kibana-7.13.3.tgz
    version: 7.13.3
  logstash:
  - apiVersion: v1
    appVersion: 7.13.3
    created: "2023-03-22T15:50:43.575561167Z"
    description: Official Elastic helm chart for Logstash
    digest: 4e398261fbb439f5b8e3c485a6de95980ff2ead2d0a48693260c6517597ade15
    home: https://github.com/elastic/helm-charts
    icon: https://helm.elastic.co/icons/logstash.png
    maintainers:
    - email: helm-charts@elastic.co
      name: Elastic
    name: logstash
    sources:
    - https://github.com/elastic/logstash
    urls:
    - https://github.com/AFC-AI2C/coeus-ltac-helm-charts.git/elk/logstash-7.13.3.tgz
    version: 7.13.3
generated: "2023-03-22T15:50:43.431772891Z"
